# Generated by Django 5.1.1 on 2024-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.CharField(max_length=255)),
                ('built_with', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_role', models.CharField(max_length=255)),
                ('contact_method', models.CharField(max_length=255)),
                ('meeting_notes', models.CharField(max_length=255)),
                ('next_step', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discovered_date', models.DateTimeField()),
                ('outreach_date', models.DateTimeField()),
                ('followup_date', models.DateTimeField()),
                ('meta', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
