# Generated by Django 5.1.1 on 2024-10-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nectar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='discovered_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='followup_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='outreach_date',
            field=models.CharField(max_length=255),
        ),
    ]
